const actionTypes = Object.freeze({
    TOGGLE_CITY: 'TOGGLE_CITY',
    CITIES_LOADING: "CITIES_LOADING",
    SET_CITIES: "SET_CITIES",
    REPORTS_LOADING: "REPORTS_LOADING",
    SET_REPORTS: "SET_REPORTS",
    SET_TEMP: "SET_TEMP",
    SET_CITIES_DATA_LIST: "SET_CITIES_DATA_LIST",
    SET_MEASUREMENT: "SET_MEASUREMENT",
    SET_RECOMEND_CITIES: "SET_RECOMEND_CITIES"
});
export default actionTypes;